name: panda-env
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  # - libcxx
  - libedit
  - libffi
  - ncurses
  - openssl
  - pip=20.1.1
  - python=3.7.7
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib

  - pip:
    - numpy==1.19.0
    - pybullet==2.8.3